---
- name: Set unit [Service] configuration
  set_fact:
    _default_service_unit:
      ExecStart: "{{ exe_dir }}/traefik {{ extra_run_args|join(' ') }}"
      User: "{{ traefik_user }}"
      Group: "{{ traefik_user }}"
      StandardOutput: journal
      StandardError: inherit
  tags:
    - preflight
    - launch

- name: Setup Traefik systemd unit
  include_role:
    name: 0x0i.systemd
  vars:
    perform_uninstall: "{{ perform_uninstall }}"
    unit_config:
      - name: "{{ _service_name }}"
        Unit:
          Description: Traefik - a dynamic service load-balancing and edge routing tool
          Documentation: https://docs.traefik.io/
          Wants: network-online.target
          After: network-online.target
        Service: "{{ _default_service_unit | combine(custom_unit_properties) }}"
        Install:
          WantedBy: multi-user.target
  tags:
    - launch

- name: Ensure start of Traefik service
  become: true
  systemd:
    name: "{{ _service_name }}"
    state: started
    enabled: "yes"
  tags:
    - launch
